---
- name: Test K8s connection
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get nodes via kubectl
      command: kubectl get nodes
      register: result

    - name: Show output
      debug:
        msg: "{{ result.stdout }}"