---
- name: Test Kubernetes Credentials
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get cluster nodes
      kubernetes.core.k8s_info:
        kind: Node
      register: nodes

    - name: Show nodes
      debug:
        msg: "Nodi nel cluster: {{ nodes.resources | map(attribute='metadata.name') | list }}"